"""Reproduce Sprint 2 against a disposable workspace, never the real fixtures."""

import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import tempfile
from datetime import datetime, timezone

from rust_checker import RULE, TIMEOUT, run
from rust_candidates import CargoContext, TextEdit, analyze_candidate


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path("fixtures/await-holding-lock")


def snapshot(root):
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in root.rglob("*") if p.is_file()}


def create_context(root):
    files = {
        "Cargo.toml": '[workspace]\nmembers = ["app", "support"]\nresolver = "2"\n',
        "Cargo.lock": '# This file is automatically @generated by Cargo.\nversion = 4\n\n'
                      '[[package]]\nname = "candidate-app"\nversion = "0.0.0"\n'
                      'dependencies = ["candidate-support"]\n\n'
                      '[[package]]\nname = "candidate-support"\nversion = "0.0.0"\n',
        ".cargo/config.toml": '[build]\nrustflags = [\'--cfg=retained_context\']\n',
        "app/Cargo.toml": '[package]\nname = "candidate-app"\nversion = "0.0.0"\n'
                          'edition = "2021"\n[dependencies]\ncandidate-support = { path = "../support" }\n'
                          '[features]\ndefault = []\nexisting = []\ncreated = []\nembedded = []\n',
        "support/Cargo.toml": '[package]\nname = "candidate-support"\nversion = "0.0.0"\nedition = "2021"\n',
        "support/src/lib.rs": 'pub const VALUE: u64 = 41;\n',
        "app/src/lib.rs": '#![allow(unexpected_cfgs)]\n'
                          '#[cfg(not(retained_context))]\ncompile_error!("lost compiler configuration");\n'
                          'mod sibling;\n'
                          '#[cfg(feature = "existing")]\npub mod existing;\n'
                          '#[cfg(feature = "created")]\npub mod created;\n'
                          '#[cfg(feature = "embedded")]\npub const TEXT: &str = include_str!("embedded.rs");\n'
                          'pub fn context_value() -> u64 { sibling::value() }\n',
        "app/src/sibling.rs": 'pub fn value() -> u64 { candidate_support::VALUE + 1 }\n',
        "app/src/existing.rs": (ROOT / FIXTURES / "good.rs").read_text(encoding="utf-8"),
    }
    for name, text in files.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode("utf-8"))


def probe():
    report = {"observed_at_utc": datetime.now(timezone.utc).isoformat(), "rule": RULE,
              "python": platform.python_version(), "platform": platform.system(),
              "timeout_seconds_per_process": TIMEOUT,
              "cases": {}, "expectations": {}}
    environment = os.environ.copy()
    report["versions"] = {}
    for name, command in (("rustc", ["rustc", "--version", "--verbose"]),
                          ("cargo", ["cargo", "--version"]),
                          ("clippy", ["cargo", "clippy", "--version"])):
        process = run(command, environment, cwd=ROOT)
        if process.returncode:
            raise RuntimeError(f"{name} version unavailable")
        report["versions"][name] = process.stdout.strip()
    good = (ROOT / FIXTURES / "good.rs").read_text(encoding="utf-8")
    bad = (ROOT / FIXTURES / "bad.rs").read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory(prefix="turnstile-original-") as temporary:
        root = Path(temporary) / "source with spaces"
        root.mkdir()
        create_context(root)
        before = snapshot(root)
        report["original_input_sha256"] = before
        existing = CargoContext(root, "app/Cargo.toml", features=("existing",))
        created = CargoContext(root, "app/Cargo.toml", features=("created",))

        def exercise(name, context, target, **proposal):
            result = analyze_candidate(context, target, **proposal)
            report["cases"][name] = result
            unchanged = snapshot(root) == before
            report["expectations"][name + "_originals_unchanged"] = unchanged
            return result

        for name, source in (("edit_bad", bad), ("edit_good", good), ("edit_bad_again", bad)):
            exercise(name, existing, "app/src/existing.rs", edits=[TextEdit(good, source)])
        for name, source in (("new_bad", bad), ("new_good", good), ("new_bad_again", bad)):
            exercise(name, created, "app/src/created.rs", content=source)
        exercise("replacement_bad", existing, "app/src/existing.rs", content=bad)
        exercise("nested_cwd_good", CargoContext(root, "app/Cargo.toml", cwd="app", features=("existing",)),
                 "app/src/existing.rs", content=good)
        build_script = root / "app/build.rs"
        build_script.write_text(
            'fn main() {\n'
            '    let manifest = std::path::PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());\n'
            '    if manifest.parent().unwrap().join(".git").exists() {\n'
            '        println!("cargo:rustc-cfg=vcs_metadata_visible");\n'
            '    }\n'
            '}\n', encoding="utf-8")
        library = root / "app/src/lib.rs"
        saved_library = library.read_bytes()
        library.write_bytes(saved_library + b'\n#[cfg(vcs_metadata_visible)]\ncompile_error!("VCS metadata reached candidate build");\n')
        git_entry = root / ".git"
        for kind in ("absent", "file", "directory"):
            if kind == "file":
                git_entry.write_text("gitdir: ../private-git-administration\n", encoding="utf-8")
            elif kind == "directory":
                git_entry.mkdir()
                (git_entry / "config").write_text("[core]\nrepositoryformatversion = 0\n", encoding="utf-8")
            before = snapshot(root)
            vcs_case = exercise("vcs_" + kind, existing, "app/src/existing.rs", content=good)
            report["expectations"]["vcs_" + kind + "_excluded"] = (
                vcs_case["outcome"] == "no_findings" and vcs_case.get("candidate_compiled") is True)
            if kind == "file":
                git_entry.unlink()
            elif kind == "directory":
                (git_entry / "config").unlink()
                git_entry.rmdir()
        build_script.unlink()
        library.write_bytes(saved_library)
        before = snapshot(root)
        exercise("edit_compile_failure", existing, "app/src/existing.rs",
                 edits=[TextEdit(good, 'pub fn broken() -> u64 { "bad" }\n')])
        exercise("new_compile_failure", created, "app/src/created.rs",
                 content='pub fn broken() -> u64 { "bad" }\n')
        exercise("unavailable", created, "app/src/created.rs", content=good,
                 cargo=str(Path(temporary) / "missing-cargo"))
        exercise("orphan", existing, "app/src/orphan.rs", content=bad)
        exercise("feature_excluded", CargoContext(root, "app/Cargo.toml"),
                 "app/src/existing.rs", content=bad)
        exercise("inner_cfg_excluded", existing, "app/src/existing.rs", content="#![cfg(any())]\n" + bad)
        exercise("embedded_not_rust", CargoContext(root, "app/Cargo.toml", features=("embedded",)),
                 "app/src/embedded.rs", content=bad)
        exercise("traversal", existing, "../escaped.rs", content=bad)
        exercise("ambiguous_edit", existing, "app/src/existing.rs", edits=[TextEdit("\n", "")])
        exercise("missing_edit", existing, "app/src/existing.rs", edits=[TextEdit("absent text", "")])
        exercise("missing_target", existing, "app/src/missing.rs", edits=[TextEdit("a", "b")])
        source_path = root / "app/src/existing.rs"
        source_saved = source_path.read_bytes()
        source_bytes = ("// café\r\n" + good.replace("\n", "\r\n")).encode("utf-8")
        source_path.write_bytes(source_bytes)
        before = snapshot(root)
        sequential = exercise("sequential_unicode_crlf", existing, "app/src/existing.rs",
                              edits=[TextEdit("café", "naïve"), TextEdit("naïve", "résumé")])
        expected_bytes = ("// résumé\r\n" + good.replace("\n", "\r\n")).encode("utf-8")
        report["expectations"]["sequential_edit_preserves_bytes"] = (
            sequential["candidate_sha256"] == hashlib.sha256(expected_bytes).hexdigest()
            and sequential["original_sha256"] == hashlib.sha256(source_bytes).hexdigest()
            and sequential["outcome"] == "no_findings")
        source_path.write_bytes(source_saved)
        before = snapshot(root)
        # The escape is a real reachable local crate, not merely a missing path.
        outside = Path(temporary) / "outside"
        (outside / "src").mkdir(parents=True)
        (outside / "Cargo.toml").write_text(
            '[package]\nname="outside"\nversion="0.0.0"\nedition="2021"\n', encoding="utf-8")
        (outside / "src/lib.rs").write_text('pub const VALUE: u64 = 9;\n', encoding="utf-8")
        outside_before = snapshot(outside)
        manifest = root / "app/Cargo.toml"
        saved = manifest.read_bytes()
        manifest.write_bytes(saved + b'\n[dev-dependencies]\noutside = { path = "../../outside" }\n')
        before = snapshot(root)
        exercise("external_dependency", existing, "app/src/existing.rs", content=bad)
        report["expectations"]["external_dependency_unchanged"] = snapshot(outside) == outside_before
        manifest.write_bytes(saved)
        before = snapshot(root)
        # Windows junctions exercise the same reparse-point boundary without
        # requiring the privilege needed to create a symlink.
        link = root / "linked"
        link_kind = None
        try:
            link.symlink_to(outside, target_is_directory=True)
            link_kind = "symlink"
        except OSError:
            if os.name == "nt":
                process = subprocess.run(["cmd", "/c", "mklink", "/J", str(link), str(outside)],
                                         capture_output=True, text=True, timeout=10)
                if process.returncode == 0:
                    link_kind = "junction"
        report["link_case"] = link_kind or "not exercised: link creation unavailable"
        if link_kind:
            try:
                result = analyze_candidate(existing, "app/src/existing.rs", content=bad)
                report["cases"]["linked_context"] = result
                report["expectations"]["linked_context_rejected"] = (
                    result["outcome"] == "checker_failure")
                report["expectations"]["linked_destination_unchanged"] = snapshot(outside) == outside_before
            finally:
                if link_kind == "junction":
                    link.rmdir()
                else:
                    link.unlink()
        cases = report["cases"]
        for name in ("edit_bad", "edit_bad_again", "new_bad", "new_bad_again", "replacement_bad"):
            expected_file = "created.rs" if name.startswith("new_") else "existing.rs"
            report["expectations"][name + "_selected_diagnostic"] = (
                cases[name]["outcome"] == "findings"
                and cases[name].get("candidate_compiled") is True
                and any((d.get("code") or {}).get("code") == RULE
                        and any(s["is_primary"] and s["line_start"] == 7
                                and s["file_name"].endswith(expected_file) for s in d["spans"])
                        for d in cases[name]["findings"]))
        for name in ("edit_good", "new_good", "nested_cwd_good"):
            report["expectations"][name + "_clean_and_compiled"] = (
                cases[name]["outcome"] == "no_findings" and cases[name].get("candidate_compiled") is True)
        for name in ("edit_compile_failure", "new_compile_failure"):
            report["expectations"][name + "_visible"] = (
                cases[name]["outcome"] == "checker_failure"
                and any((d.get("code") or {}).get("code") == "E0308" for d in cases[name].get("diagnostics", [])))
        for name in ("unavailable", "traversal", "ambiguous_edit", "missing_edit", "missing_target", "external_dependency"):
            report["expectations"][name + "_rejected"] = cases[name]["outcome"] == "checker_failure"
        for name in ("orphan", "feature_excluded", "inner_cfg_excluded", "embedded_not_rust"):
            report["expectations"][name + "_not_claimed_analyzed"] = (
                cases[name]["outcome"] == "checker_failure" and cases[name].get("error") == "candidate_not_compiled")
    report["input_sha256"] = {
        name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest()
        for name in ("tools/rust_candidates.py", "tools/rust_attribution.py", "tools/probe_rust_candidates.py", "tools/rust_checker.py",
                     "fixtures/await-holding-lock/bad.rs", "fixtures/await-holding-lock/good.rs")}
    report["passed"] = all(report["expectations"].values())
    serialized = json.dumps(report, indent=2)
    for old, new in ((str(root), "<original>"), (root.as_posix(), "<original>"),
                     (temporary, "<probe>"), (Path(temporary).as_posix(), "<probe>")):
        serialized = serialized.replace(json.dumps(old)[1:-1], new)
    print(serialized)
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(probe())
